on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - edited
      - synchronize
  push:
    branches:
      - main

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-22.04

  security_scanners:
    name: Security Scanners
    runs-on: ubuntu-22.04

  tests:
    name: Tests
    runs-on: ubuntu-22.04